# see https://docs.travis-ci.com/user/languages/android/
language: android
sudo: false
jdk:
  - oraclejdk8
before_install:
  - yes | /usr/local/android-sdk/tools/bin/sdkmanager --licenses
android:
  components:
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra
script:
  #- ./gradlew assembleDebug --info
  - ./gradlew assembleRelease --info